# Generated by Django 3.0.5 on 2020-04-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groceryItem',
            new_name='grocery_item',
        ),
    ]
