# Generated by Django 3.0.5 on 2020-04-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingList', '0002_auto_20200419_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grocery_item',
            new_name='GroceryItem',
        ),
    ]
