version: '3.7'

services:
  web:
    build: ./
    command: python ./manage.py runserver 0:8080
    volumes:
      - .:/home/djangoadmin/djangoapps/ana1/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
volumes:
  postgres_data: